<?php

namespace Database\Seeders;

use App\Models\Country;
use Filament\Tables\Columns\Summarizers\Count;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        Country::truncate();
        $countries = [

            
            'Saudi Arabia' => ['name' => ['en' => 'Saudi Arabia', 'ar' => 'المملكة العربية السعودية'], 'code' => '966', 'flag' => '🇸🇦', 'currency' => 'SAR'],
            'Algeria' => ['name' => ['en' => 'Algeria', 'ar' => 'الجزائر'], 'code' => '213', 'flag' => '🇩🇿', 'currency' => 'DZD'],
            'Bahrain' => ['name' => ['en' => 'Bahrain', 'ar' => 'البحرين'], 'code' => '973', 'flag' => '🇧🇭', 'currency' => 'BHD'],
            'Egypt' => ['name' => ['en' => 'Egypt', 'ar' => 'مصر'], 'code' => '20', 'flag' => '🇪🇬', 'currency' => 'EGP'],
            'Iran' => ['name' => ['en' => 'Iran', 'ar' => 'إيران'], 'code' => '98', 'flag' => '🇮🇷', 'currency' => 'IRR'],
            'Iraq' => ['name' => ['en' => 'Iraq', 'ar' => 'العراق'], 'code' => '964', 'flag' => '🇮🇶', 'currency' => 'IQD'],
            'Jordan' => ['name' => ['en' => 'Jordan', 'ar' => 'الأردن'], 'code' => '962', 'flag' => '🇯🇴', 'currency' => 'JOD'],
            'Kuwait' => ['name' => ['en' => 'Kuwait', 'ar' => 'الكويت'], 'code' => '965', 'flag' => '🇰🇼', 'currency' => 'KWD'],
            'Lebanon' => ['name' => ['en' => 'Lebanon', 'ar' => 'لبنان'], 'code' => '961', 'flag' => '🇱🇧', 'currency' => 'LBP'],
            'Libya' => ['name' => ['en' => 'Libya', 'ar' => 'ليبيا'], 'code' => '218', 'flag' => '🇱🇾', 'currency' => 'LYD'],
            'Morocco' => ['name' => ['en' => 'Morocco', 'ar' => 'المغرب'], 'code' => '212', 'flag' => '🇲🇦', 'currency' => 'MAD'],
            'Oman' => ['name' => ['en' => 'Oman', 'ar' => 'عمان'], 'code' => '968', 'flag' => '🇴🇲', 'currency' => 'OMR'],
            'Palestine' => ['name' => ['en' => 'Palestine', 'ar' => 'فلسطين'], 'code' => '970', 'flag' => '🇵🇸', 'currency' => 'ILS'],
            'Qatar' => ['name' => ['en' => 'Qatar', 'ar' => 'قطر'], 'code' => '974', 'flag' => '🇶🇦', 'currency' => 'QAR'],
            'Sudan' => ['name' => ['en' => 'Sudan', 'ar' => 'السودان'], 'code' => '249', 'flag' => '🇸🇩', 'currency' => 'SDG'],
            'Syria' => ['name' => ['en' => 'Syria', 'ar' => 'سوريا'], 'code' => '963', 'flag' => '🇸🇾', 'currency' => 'SYP'],
            'Tunisia' => ['name' => ['en' => 'Tunisia', 'ar' => 'تونس'], 'code' => '216', 'flag' => '🇹🇳', 'currency' => 'TND'],
            'UAE' => ['name' => ['en' => 'United Arab Emirates', 'ar' => 'الإمارات العربية المتحدة'], 'code' => '971', 'flag' => '🇦🇪', 'currency' => 'AED'],
            'Yemen' => ['name' => ['en' => 'Yemen', 'ar' => 'اليمن'], 'code' => '967', 'flag' => '🇾🇪', 'currency' => 'YER'],

            'Afghanistan' => ['name' => ['en' => 'Afghanistan', 'ar' => 'أفغانستان'], 'code' => '93', 'flag' => '🇦🇫', 'currency' => 'AFN'],
            'Angola' => ['name' => ['en' => 'Angola', 'ar' => 'أنغولا'], 'code' => '244', 'flag' => '🇦🇴', 'currency' => 'AOA'],
            'Benin' => ['name' => ['en' => 'Benin', 'ar' => 'بنين'], 'code' => '229', 'flag' => '🇧🇯', 'currency' => 'XOF'],
            'Botswana' => ['name' => ['en' => 'Botswana', 'ar' => 'بوتسوانا'], 'code' => '267', 'flag' => '🇧🇼', 'currency' => 'BWP'],
            'Burkina Faso' => ['name' => ['en' => 'Burkina Faso', 'ar' => 'بوركينا فاسو'], 'code' => '226', 'flag' => '🇧🇫', 'currency' => 'XOF'],
            'Burundi' => ['name' => ['en' => 'Burundi', 'ar' => 'بوروندي'], 'code' => '257', 'flag' => '🇧🇮', 'currency' => 'BIF'],
            'Cameroon' => ['name' => ['en' => 'Cameroon', 'ar' => 'الكاميرون'], 'code' => '237', 'flag' => '🇨🇲', 'currency' => 'XAF'],
            'Cape Verde' => ['name' => ['en' => 'Cape Verde', 'ar' => 'الرأس الأخضر'], 'code' => '238', 'flag' => '🇨🇻', 'currency' => 'CVE'],
            'Central African Republic' => ['name' => ['en' => 'Central African Republic', 'ar' => 'جمهورية أفريقيا الوسطى'], 'code' => '236', 'flag' => '🇨🇫', 'currency' => 'XAF'],
            'Chad' => ['name' => ['en' => 'Chad', 'ar' => 'تشاد'], 'code' => '235', 'flag' => '🇹🇩', 'currency' => 'XAF'],
            'Comoros' => ['name' => ['en' => 'Comoros', 'ar' => 'جزر القمر'], 'code' => '269', 'flag' => '🇰🇲', 'currency' => 'KMF'],
            'Congo' => ['name' => ['en' => 'Congo', 'ar' => 'الكونغو'], 'code' => '242', 'flag' => '🇨🇬', 'currency' => 'XAF'],
            'DR Congo' => ['name' => ['en' => 'DR Congo', 'ar' => 'جمهورية الكونغو الديمقراطية'], 'code' => '243', 'flag' => '🇨🇩', 'currency' => 'CDF'],
            'Djibouti' => ['name' => ['en' => 'Djibouti', 'ar' => 'جيبوتي'], 'code' => '253', 'flag' => '🇩🇯', 'currency' => 'DJF'],
            'Equatorial Guinea' => ['name' => ['en' => 'Equatorial Guinea', 'ar' => 'غينيا الاستوائية'], 'code' => '240', 'flag' => '🇬🇶', 'currency' => 'XAF'],
            'Eritrea' => ['name' => ['en' => 'Eritrea', 'ar' => 'إريتريا'], 'code' => '291', 'flag' => '🇪🇷', 'currency' => 'ERN'],
            'Eswatini' => ['name' => ['en' => 'Eswatini', 'ar' => 'إسواتيني'], 'code' => '268', 'flag' => '🇸🇿', 'currency' => 'SZL'],
            'Ethiopia' => ['name' => ['en' => 'Ethiopia', 'ar' => 'إثيوبيا'], 'code' => '251', 'flag' => '🇪🇹', 'currency' => 'ETB'],
            'Gabon' => ['name' => ['en' => 'Gabon', 'ar' => 'الغابون'], 'code' => '241', 'flag' => '🇬🇦', 'currency' => 'XAF'],
            'Gambia' => ['name' => ['en' => 'Gambia', 'ar' => 'غامبيا'], 'code' => '220', 'flag' => '🇬🇲', 'currency' => 'GMD'],
            'Ghana' => ['name' => ['en' => 'Ghana', 'ar' => 'غانا'], 'code' => '233', 'flag' => '🇬🇭', 'currency' => 'GHS'],
            'Guinea' => ['name' => ['en' => 'Guinea', 'ar' => 'غينيا'], 'code' => '224', 'flag' => '🇬🇳', 'currency' => 'GNF'],
            'Guinea-Bissau' => ['name' => ['en' => 'Guinea-Bissau', 'ar' => 'غينيا بيساو'], 'code' => '245', 'flag' => '🇬🇼', 'currency' => 'XOF'],
            'Ivory Coast' => ['name' => ['en' => 'Ivory Coast', 'ar' => 'ساحل العاج'], 'code' => '225', 'flag' => '🇨🇮', 'currency' => 'XOF'],
            'Kenya' => ['name' => ['en' => 'Kenya', 'ar' => 'كينيا'], 'code' => '254', 'flag' => '🇰🇪', 'currency' => 'KES'],
            'Lesotho' => ['name' => ['en' => 'Lesotho', 'ar' => 'ليسوتو'], 'code' => '266', 'flag' => '🇱🇸', 'currency' => 'LSL'],
            'Liberia' => ['name' => ['en' => 'Liberia', 'ar' => 'ليبيريا'], 'code' => '231', 'flag' => '🇱🇷', 'currency' => 'LRD'],
            'Madagascar' => ['name' => ['en' => 'Madagascar', 'ar' => 'مدغشقر'], 'code' => '261', 'flag' => '🇲🇬', 'currency' => 'MGA'],



            
            'Malawi' => ['name' => ['en' => 'Malawi', 'ar' => 'مالاوي'], 'code' => '265', 'flag' => '🇲🇼', 'currency' => 'MWK'],
            'Mali' => ['name' => ['en' => 'Mali', 'ar' => 'مالي'], 'code' => '223', 'flag' => '🇲🇱', 'currency' => 'XOF'],
            'Mauritania' => ['name' => ['en' => 'Mauritania', 'ar' => 'موريتانيا'], 'code' => '222', 'flag' => '🇲🇷', 'currency' => 'MRU'],
            'Mauritius' => ['name' => ['en' => 'Mauritius', 'ar' => 'موريشيوس'], 'code' => '230', 'flag' => '🇲🇺', 'currency' => 'MUR'],
            'Mozambique' => ['name' => ['en' => 'Mozambique', 'ar' => 'موزمبيق'], 'code' => '258', 'flag' => '🇲🇿', 'currency' => 'MZN'],
            'Namibia' => ['name' => ['en' => 'Namibia', 'ar' => 'ناميبيا'], 'code' => '264', 'flag' => '🇳🇦', 'currency' => 'NAD'],
            'Niger' => ['name' => ['en' => 'Niger', 'ar' => 'النيجر'], 'code' => '227', 'flag' => '🇳🇪', 'currency' => 'XOF'],
            'Nigeria' => ['name' => ['en' => 'Nigeria', 'ar' => 'نيجيريا'], 'code' => '234', 'flag' => '🇳🇬', 'currency' => 'NGN'],
            'Rwanda' => ['name' => ['en' => 'Rwanda', 'ar' => 'رواندا'], 'code' => '250', 'flag' => '🇷🇼', 'currency' => 'RWF'],
            'Sao Tome and Principe' => ['name' => ['en' => 'Sao Tome and Principe', 'ar' => 'ساو تومي وبرينسيبي'], 'code' => '239', 'flag' => '🇸🇹', 'currency' => 'STN'],
            'Senegal' => ['name' => ['en' => 'Senegal', 'ar' => 'السنغال'], 'code' => '221', 'flag' => '🇸🇳', 'currency' => 'XOF'],
            'Seychelles' => ['name' => ['en' => 'Seychelles', 'ar' => 'سيشل'], 'code' => '248', 'flag' => '🇸🇨', 'currency' => 'SCR'],
            'Sierra Leone' => ['name' => ['en' => 'Sierra Leone', 'ar' => 'سيراليون'], 'code' => '232', 'flag' => '🇸🇱', 'currency' => 'SLL'],
            'Somalia' => ['name' => ['en' => 'Somalia', 'ar' => 'الصومال'], 'code' => '252', 'flag' => '🇸🇴', 'currency' => 'SOS'],
            'South Africa' => ['name' => ['en' => 'South Africa', 'ar' => 'جنوب أفريقيا'], 'code' => '27', 'flag' => '🇿🇦', 'currency' => 'ZAR'],
            'South Sudan' => ['name' => ['en' => 'South Sudan', 'ar' => 'جنوب السودان'], 'code' => '211', 'flag' => '🇸🇸', 'currency' => 'SSP'],
            'Tanzania' => ['name' => ['en' => 'Tanzania', 'ar' => 'تنزانيا'], 'code' => '255', 'flag' => '🇹🇿', 'currency' => 'TZS'],
            'Togo' => ['name' => ['en' => 'Togo', 'ar' => 'توغو'], 'code' => '228', 'flag' => '🇹🇬', 'currency' => 'XOF'],
            'Uganda' => ['name' => ['en' => 'Uganda', 'ar' => 'أوغندا'], 'code' => '256', 'flag' => '🇺🇬', 'currency' => 'UGX'],
            'Zambia' => ['name' => ['en' => 'Zambia', 'ar' => 'زامبيا'], 'code' => '260', 'flag' => '🇿🇲', 'currency' => 'ZMW'],
            'Zimbabwe' => ['name' => ['en' => 'Zimbabwe', 'ar' => 'زيمبابوي'], 'code' => '263', 'flag' => '🇿🇼', 'currency' => 'ZWL'],

            'Albania' => ['name' => ['en' => 'Albania', 'ar' => 'ألبانيا'], 'code' => '355', 'flag' => '🇦🇱', 'currency' => 'ALL'],
            'Andorra' => ['name' => ['en' => 'Andorra', 'ar' => 'أندورا'], 'code' => '376', 'flag' => '🇦🇩', 'currency' => 'EUR'],
            'Armenia' => ['name' => ['en' => 'Armenia', 'ar' => 'أرمينيا'], 'code' => '374', 'flag' => '🇦🇲', 'currency' => 'AMD'],
            'Austria' => ['name' => ['en' => 'Austria', 'ar' => 'النمسا'], 'code' => '43', 'flag' => '🇦🇹', 'currency' => 'EUR'],
            'Azerbaijan' => ['name' => ['en' => 'Azerbaijan', 'ar' => 'أذربيجان'], 'code' => '994', 'flag' => '🇦🇿', 'currency' => 'AZN'],
            'Belarus' => ['name' => ['en' => 'Belarus', 'ar' => 'بيلاروسيا'], 'code' => '375', 'flag' => '🇧🇾', 'currency' => 'BYN'],
            'Belgium' => ['name' => ['en' => 'Belgium', 'ar' => 'بلجيكا'], 'code' => '32', 'flag' => '🇧🇪', 'currency' => 'EUR'],
            'Bosnia and Herzegovina' => ['name' => ['en' => 'Bosnia and Herzegovina', 'ar' => 'البوسنة والهرسك'], 'code' => '387', 'flag' => '🇧🇦', 'currency' => 'BAM'],
            'Bulgaria' => ['name' => ['en' => 'Bulgaria', 'ar' => 'بلغاريا'], 'code' => '359', 'flag' => '🇧🇬', 'currency' => 'BGN'],
            'Croatia' => ['name' => ['en' => 'Croatia', 'ar' => 'كرواتيا'], 'code' => '385', 'flag' => '🇭🇷', 'currency' => 'EUR'],
            'Cyprus' => ['name' => ['en' => 'Cyprus', 'ar' => 'قبرص'], 'code' => '357', 'flag' => '🇨🇾', 'currency' => 'EUR'],
            'Czech Republic' => ['name' => ['en' => 'Czech Republic', 'ar' => 'جمهورية التشيك'], 'code' => '420', 'flag' => '🇨🇿', 'currency' => 'CZK'],
            'Denmark' => ['name' => ['en' => 'Denmark', 'ar' => 'الدنمارك'], 'code' => '45', 'flag' => '🇩🇰', 'currency' => 'DKK'],
            'Estonia' => ['name' => ['en' => 'Estonia', 'ar' => 'إستونيا'], 'code' => '372', 'flag' => '🇪🇪', 'currency' => 'EUR'],
            'Finland' => ['name' => ['en' => 'Finland', 'ar' => 'فنلندا'], 'code' => '358', 'flag' => '🇫🇮', 'currency' => 'EUR'],
            'France' => ['name' => ['en' => 'France', 'ar' => 'فرنسا'], 'code' => '33', 'flag' => '🇫🇷', 'currency' => 'EUR'],
            'Georgia' => ['name' => ['en' => 'Georgia', 'ar' => 'جورجيا'], 'code' => '995', 'flag' => '🇬🇪', 'currency' => 'GEL'],
            'Germany' => ['name' => ['en' => 'Germany', 'ar' => 'ألمانيا'], 'code' => '49', 'flag' => '🇩🇪', 'currency' => 'EUR'],
            'Greece' => ['name' => ['en' => 'Greece', 'ar' => 'اليونان'], 'code' => '30', 'flag' => '🇬🇷', 'currency' => 'EUR'],
            'Hungary' => ['name' => ['en' => 'Hungary', 'ar' => 'المجر'], 'code' => '36', 'flag' => '🇭🇺', 'currency' => 'HUF'],
            'Iceland' => ['name' => ['en' => 'Iceland', 'ar' => 'آيسلندا'], 'code' => '354', 'flag' => '🇮🇸', 'currency' => 'ISK'],
            'Ireland' => ['name' => ['en' => 'Ireland', 'ar' => 'أيرلندا'], 'code' => '353', 'flag' => '🇮🇪', 'currency' => 'EUR'],
            'Italy' => ['name' => ['en' => 'Italy', 'ar' => 'إيطاليا'], 'code' => '39', 'flag' => '🇮🇹', 'currency' => 'EUR'],
            'Kazakhstan' => ['name' => ['en' => 'Kazakhstan', 'ar' => 'كازاخستان'], 'code' => '7', 'flag' => '🇰🇿', 'currency' => 'KZT'],
            'Kosovo' => ['name' => ['en' => 'Kosovo', 'ar' => 'كوسوفو'], 'code' => '383', 'flag' => '🇽🇰', 'currency' => 'EUR'],
            'Latvia' => ['name' => ['en' => 'Latvia', 'ar' => 'لاتفيا'], 'code' => '371', 'flag' => '🇱🇻', 'currency' => 'EUR'],
            'Liechtenstein' => ['name' => ['en' => 'Liechtenstein', 'ar' => 'ليختنشتاين'], 'code' => '423', 'flag' => '🇱🇮', 'currency' => 'CHF'],
            'Lithuania' => ['name' => ['en' => 'Lithuania', 'ar' => 'ليتوانيا'], 'code' => '370', 'flag' => '🇱🇹', 'currency' => 'EUR'],
            'Luxembourg' => ['name' => ['en' => 'Luxembourg', 'ar' => 'لوكسمبورغ'], 'code' => '352', 'flag' => '🇱🇺', 'currency' => 'EUR'],
            'Malta' => ['name' => ['en' => 'Malta', 'ar' => 'مالطا'], 'code' => '356', 'flag' => '🇲🇹', 'currency' => 'EUR'],
            'Moldova' => ['name' => ['en' => 'Moldova', 'ar' => 'مولدوفا'], 'code' => '373', 'flag' => '🇲🇩', 'currency' => 'MDL'],
            'Monaco' => ['name' => ['en' => 'Monaco', 'ar' => 'موناكو'], 'code' => '377', 'flag' => '🇲🇨', 'currency' => 'EUR'],
            'Montenegro' => ['name' => ['en' => 'Montenegro', 'ar' => 'الجبل الأسود'], 'code' => '382', 'flag' => '🇲🇪', 'currency' => 'EUR'],
            'Netherlands' => ['name' => ['en' => 'Netherlands', 'ar' => 'هولندا'], 'code' => '31', 'flag' => '🇳🇱', 'currency' => 'EUR'],
            'North Macedonia' => ['name' => ['en' => 'North Macedonia', 'ar' => 'مقدونيا الشمالية'], 'code' => '389', 'flag' => '🇲🇰', 'currency' => 'MKD'],
            'Norway' => ['name' => ['en' => 'Norway', 'ar' => 'النرويج'], 'code' => '47', 'flag' => '🇳🇴', 'currency' => 'NOK'],
            'Poland' => ['name' => ['en' => 'Poland', 'ar' => 'بولندا'], 'code' => '48', 'flag' => '🇵🇱', 'currency' => 'PLN'],
            'Portugal' => ['name' => ['en' => 'Portugal', 'ar' => 'البرتغال'], 'code' => '351', 'flag' => '🇵🇹', 'currency' => 'EUR'],
            'Romania' => ['name' => ['en' => 'Romania', 'ar' => 'رومانيا'], 'code' => '40', 'flag' => '🇷🇴', 'currency' => 'RON'],
            'Russia' => ['name' => ['en' => 'Russia', 'ar' => 'روسيا'], 'code' => '7', 'flag' => '🇷🇺', 'currency' => 'RUB'],
            'San Marino' => ['name' => ['en' => 'San Marino', 'ar' => 'سان مارينو'], 'code' => '378', 'flag' => '🇸🇲', 'currency' => 'EUR'],
            'Serbia' => ['name' => ['en' => 'Serbia', 'ar' => 'صربيا'], 'code' => '381', 'flag' => '🇷🇸', 'currency' => 'RSD'],
            'Slovakia' => ['name' => ['en' => 'Slovakia', 'ar' => 'سلوفاكيا'], 'code' => '421', 'flag' => '🇸🇰', 'currency' => 'EUR'],
            'Slovenia' => ['name' => ['en' => 'Slovenia', 'ar' => 'سلوفينيا'], 'code' => '386', 'flag' => '🇸🇮', 'currency' => 'EUR'],
            'Spain' => ['name' => ['en' => 'Spain', 'ar' => 'إسبانيا'], 'code' => '34', 'flag' => '🇪🇸', 'currency' => 'EUR'],
            'Sweden' => ['name' => ['en' => 'Sweden', 'ar' => 'السويد'], 'code' => '46', 'flag' => '🇸🇪', 'currency' => 'SEK'],
            'Switzerland' => ['name' => ['en' => 'Switzerland', 'ar' => 'سويسرا'], 'code' => '41', 'flag' => '🇨🇭', 'currency' => 'CHF'],
            'Ukraine' => ['name' => ['en' => 'Ukraine', 'ar' => 'أوكرانيا'], 'code' => '380', 'flag' => '🇺🇦', 'currency' => 'UAH'],
            'United Kingdom' => ['name' => ['en' => 'United Kingdom', 'ar' => 'المملكة المتحدة'], 'code' => '44', 'flag' => '🇬🇧', 'currency' => 'GBP'],
            'Vatican City' => ['name' => ['en' => 'Vatican City', 'ar' => 'الفاتيكان'], 'code' => '379', 'flag' => '🇻🇦', 'currency' => 'EUR'],


            'Antigua and Barbuda' => ['name' => ['en' => 'Antigua and Barbuda', 'ar' => 'أنتيغوا وباربودا'], 'code' => '1', 'flag' => '🇦🇬', 'currency' => 'XCD'],
            'Argentina' => ['name' => ['en' => 'Argentina', 'ar' => 'الأرجنتين'], 'code' => '54', 'flag' => '🇦🇷', 'currency' => 'ARS'],
            'Bahamas' => ['name' => ['en' => 'Bahamas', 'ar' => 'الباهاما'], 'code' => '1', 'flag' => '🇧🇸', 'currency' => 'BSD'],
            'Barbados' => ['name' => ['en' => 'Barbados', 'ar' => 'بربادوس'], 'code' => '1', 'flag' => '🇧🇧', 'currency' => 'BBD'],
            'Belize' => ['name' => ['en' => 'Belize', 'ar' => 'بليز'], 'code' => '501', 'flag' => '🇧🇿', 'currency' => 'BZD'],
            'Bolivia' => ['name' => ['en' => 'Bolivia', 'ar' => 'بوليفيا'], 'code' => '591', 'flag' => '🇧🇴', 'currency' => 'BOB'],
            'Brazil' => ['name' => ['en' => 'Brazil', 'ar' => 'البرازيل'], 'code' => '55', 'flag' => '🇧🇷', 'currency' => 'BRL'],
            'Canada' => ['name' => ['en' => 'Canada', 'ar' => 'كندا'], 'code' => '1', 'flag' => '🇨🇦', 'currency' => 'CAD'],
            'Chile' => ['name' => ['en' => 'Chile', 'ar' => 'تشيلي'], 'code' => '56', 'flag' => '🇨🇱', 'currency' => 'CLP'],
            'Colombia' => ['name' => ['en' => 'Colombia', 'ar' => 'كولومبيا'], 'code' => '57', 'flag' => '🇨🇴', 'currency' => 'COP'],
            'Costa Rica' => ['name' => ['en' => 'Costa Rica', 'ar' => 'كوستاريكا'], 'code' => '506', 'flag' => '🇨🇷', 'currency' => 'CRC'],
            'Cuba' => ['name' => ['en' => 'Cuba', 'ar' => 'كوبا'], 'code' => '53', 'flag' => '🇨🇺', 'currency' => 'CUP'],
            'Dominica' => ['name' => ['en' => 'Dominica', 'ar' => 'دومينيكا'], 'code' => '1', 'flag' => '🇩🇲', 'currency' => 'XCD'],
            'Dominican Republic' => ['name' => ['en' => 'Dominican Republic', 'ar' => 'جمهورية الدومينيكان'], 'code' => '1', 'flag' => '🇩🇴', 'currency' => 'DOP'],
            'Ecuador' => ['name' => ['en' => 'Ecuador', 'ar' => 'الإكوادور'], 'code' => '593', 'flag' => '🇪🇨', 'currency' => 'USD'],
            'El Salvador' => ['name' => ['en' => 'El Salvador', 'ar' => 'السلفادور'], 'code' => '503', 'flag' => '🇸🇻', 'currency' => 'SVC'],
            'Grenada' => ['name' => ['en' => 'Grenada', 'ar' => 'غرينادا'], 'code' => '1', 'flag' => '🇬🇩', 'currency' => 'XCD'],
            'Guatemala' => ['name' => ['en' => 'Guatemala', 'ar' => 'غواتيمالا'], 'code' => '502', 'flag' => '🇬🇹', 'currency' => 'GTQ'],
            'Guyana' => ['name' => ['en' => 'Guyana', 'ar' => 'غيانا'], 'code' => '592', 'flag' => '🇬🇾', 'currency' => 'GYD'],
            'Haiti' => ['name' => ['en' => 'Haiti', 'ar' => 'هايتي'], 'code' => '509', 'flag' => '🇭🇹', 'currency' => 'HTG'],
            'Honduras' => ['name' => ['en' => 'Honduras', 'ar' => 'هندوراس'], 'code' => '504', 'flag' => '🇭🇳', 'currency' => 'HNL'],
            'Jamaica' => ['name' => ['en' => 'Jamaica', 'ar' => 'جامايكا'], 'code' => '1', 'flag' => '🇯🇲', 'currency' => 'JMD'],
            'Mexico' => ['name' => ['en' => 'Mexico', 'ar' => 'المكسيك'], 'code' => '52', 'flag' => '🇲🇽', 'currency' => 'MXN'],
            'Nicaragua' => ['name' => ['en' => 'Nicaragua', 'ar' => 'نيكاراغوا'], 'code' => '505', 'flag' => '🇳🇮', 'currency' => 'NIO'],
            'Panama' => ['name' => ['en' => 'Panama', 'ar' => 'بنما'], 'code' => '507', 'flag' => '🇵🇦', 'currency' => 'PAB'],
            'Paraguay' => ['name' => ['en' => 'Paraguay', 'ar' => 'باراغواي'], 'code' => '595', 'flag' => '🇵🇾', 'currency' => 'PYG'],
            'Peru' => ['name' => ['en' => 'Peru', 'ar' => 'بيرو'], 'code' => '51', 'flag' => '🇵🇪', 'currency' => 'PEN'],
            'Saint Kitts and Nevis' => ['name' => ['en' => 'Saint Kitts and Nevis', 'ar' => 'سانت كيتس ونيفيس'], 'code' => '1', 'flag' => '🇰🇳', 'currency' => 'XCD'],
            'Saint Lucia' => ['name' => ['en' => 'Saint Lucia', 'ar' => 'سانت لوسيا'], 'code' => '1', 'flag' => '🇱🇨', 'currency' => 'XCD'],
            'Saint Vincent and the Grenadines' => ['name' => ['en' => 'Saint Vincent and the Grenadines', 'ar' => 'سانت فنسنت والغرينادين'], 'code' => '1', 'flag' => '🇻🇨', 'currency' => 'XCD'],
            'Suriname' => ['name' => ['en' => 'Suriname', 'ar' => 'سورينام'], 'code' => '597', 'flag' => '🇸🇷', 'currency' => 'SRD'],
            'Trinidad and Tobago' => ['name' => ['en' => 'Trinidad and Tobago', 'ar' => 'ترينيداد وتوباغو'], 'code' => '1', 'flag' => '🇹🇹', 'currency' => 'TTD'],
            'United States' => ['name' => ['en' => 'United States', 'ar' => 'الولايات المتحدة'], 'code' => '1', 'flag' => '🇺🇸', 'currency' => 'USD'],
            'Uruguay' => ['name' => ['en' => 'Uruguay', 'ar' => 'أوروغواي'], 'code' => '598', 'flag' => '🇺🇾', 'currency' => 'UYU'],
            'Venezuela' => ['name' => ['en' => 'Venezuela', 'ar' => 'فنزويلا'], 'code' => '58', 'flag' => '🇻🇪', 'currency' => 'VES'],

            // Asia-Pacific (New)
            'Australia' => ['name' => ['en' => 'Australia', 'ar' => 'أستراليا'], 'code' => '61', 'flag' => '🇦🇺', 'currency' => 'AUD'],
            'Bangladesh' => ['name' => ['en' => 'Bangladesh', 'ar' => 'بنغلاديش'], 'code' => '880', 'flag' => '🇧🇩', 'currency' => 'BDT'],
            'Bhutan' => ['name' => ['en' => 'Bhutan', 'ar' => 'بوتان'], 'code' => '975', 'flag' => '🇧🇹', 'currency' => 'INR'],
            'Brunei' => ['name' => ['en' => 'Brunei', 'ar' => 'بروناي'], 'code' => '673', 'flag' => '🇧🇳', 'currency' => 'BND'],
            'Cambodia' => ['name' => ['en' => 'Cambodia', 'ar' => 'كمبوديا'], 'code' => '855', 'flag' => '🇰🇭', 'currency' => 'KHR'],
            'China' => ['name' => ['en' => 'China', 'ar' => 'الصين'], 'code' => '86', 'flag' => '🇨🇳', 'currency' => 'CNY'],
            'Fiji' => ['name' => ['en' => 'Fiji', 'ar' => 'فيجي'], 'code' => '679', 'flag' => '🇫🇯', 'currency' => 'FJD'],
            'India' => ['name' => ['en' => 'India', 'ar' => 'الهند'], 'code' => '91', 'flag' => '🇮🇳', 'currency' => 'INR'],
            'Indonesia' => ['name' => ['en' => 'Indonesia', 'ar' => 'إندونيسيا'], 'code' => '62', 'flag' => '🇮🇩', 'currency' => 'IDR'],
            'Japan' => ['name' => ['en' => 'Japan', 'ar' => 'اليابان'], 'code' => '81', 'flag' => '🇯🇵', 'currency' => 'JPY'],
            'Kiribati' => ['name' => ['en' => 'Kiribati', 'ar' => 'كيريباتي'], 'code' => '686', 'flag' => '🇰🇮', 'currency' => 'AUD'],
            'Laos' => ['name' => ['en' => 'Laos', 'ar' => 'لاوس'], 'code' => '856', 'flag' => '🇱🇦', 'currency' => 'LAK'],
            'Malaysia' => ['name' => ['en' => 'Malaysia', 'ar' => 'ماليزيا'], 'code' => '60', 'flag' => '🇲🇾', 'currency' => 'MYR'],
            'Maldives' => ['name' => ['en' => 'Maldives', 'ar' => 'جزر المالديف'], 'code' => '960', 'flag' => '🇲🇻', 'currency' => 'MVR'],
            'Marshall Islands' => ['name' => ['en' => 'Marshall Islands', 'ar' => 'جزر مارشال'], 'code' => '692', 'flag' => '🇲🇭', 'currency' => 'USD'],
            'Micronesia' => ['name' => ['en' => 'Micronesia', 'ar' => 'ميكرونيزيا'], 'code' => '691', 'flag' => '🇫🇲', 'currency' => 'USD'],
            'Myanmar' => ['name' => ['en' => 'Myanmar', 'ar' => 'ميانمار'], 'code' => '95', 'flag' => '🇲🇲', 'currency' => 'MMK'],
            'Nauru' => ['name' => ['en' => 'Nauru', 'ar' => 'ناورو'], 'code' => '674', 'flag' => '🇳🇷', 'currency' => 'AUD'],
            'Nepal' => ['name' => ['en' => 'Nepal', 'ar' => 'نيبال'], 'code' => '977', 'flag' => '🇳🇵', 'currency' => 'NPR'],
            'New Zealand' => ['name' => ['en' => 'New Zealand', 'ar' => 'نيوزيلندا'], 'code' => '64', 'flag' => '🇳🇿', 'currency' => 'NZD'],
            'North Korea' => ['name' => ['en' => 'North Korea', 'ar' => 'كوريا الشمالية'], 'code' => '850', 'flag' => '🇰🇵', 'currency' => 'KPW'],
            'Pakistan' => ['name' => ['en' => 'Pakistan', 'ar' => 'باكستان'], 'code' => '92', 'flag' => '🇵🇰', 'currency' => 'PKR'],
            'Palau' => ['name' => ['en' => 'Palau', 'ar' => 'بالاو'], 'code' => '680', 'flag' => '🇵🇼', 'currency' => 'USD'],
            'Papua New Guinea' => ['name' => ['en' => 'Papua New Guinea', 'ar' => 'بابوا غينيا الجديدة'], 'code' => '675', 'flag' => '🇵🇬', 'currency' => 'PGK'],
            'Philippines' => ['name' => ['en' => 'Philippines', 'ar' => 'الفلبين'], 'code' => '63', 'flag' => '🇵🇭', 'currency' => 'PHP'],
            'Samoa' => ['name' => ['en' => 'Samoa', 'ar' => 'ساموا'], 'code' => '685', 'flag' => '🇼🇸', 'currency' => 'WST'],
            'Singapore' => ['name' => ['en' => 'Singapore', 'ar' => 'سنغافورة'], 'code' => '65', 'flag' => '🇸🇬', 'currency' => 'SGD'],
            'Solomon Islands' => ['name' => ['en' => 'Solomon Islands', 'ar' => 'جزر سليمان'], 'code' => '677', 'flag' => '🇸🇧', 'currency' => 'SBD'],
            'South Korea' => ['name' => ['en' => 'South Korea', 'ar' => 'كوريا الجنوبية'], 'code' => '82', 'flag' => '🇰🇷', 'currency' => 'KRW'],
            'Sri Lanka' => ['name' => ['en' => 'Sri Lanka', 'ar' => 'سريلانكا'], 'code' => '94', 'flag' => '🇱🇰', 'currency' => 'LKR'],
            'Taiwan' => ['name' => ['en' => 'Taiwan', 'ar' => 'تايوان'], 'code' => '886', 'flag' => '🇹🇼', 'currency' => 'TWD'],
            'Thailand' => ['name' => ['en' => 'Thailand', 'ar' => 'تايلاند'], 'code' => '66', 'flag' => '🇹🇭', 'currency' => 'THB'],
            'Timor-Leste' => ['name' => ['en' => 'Timor-Leste', 'ar' => 'تيمور الشرقية'], 'code' => '670', 'flag' => '🇹🇱', 'currency' => 'USD'],
            'Tonga' => ['name' => ['en' => 'Tonga', 'ar' => 'تونغا'], 'code' => '676', 'flag' => '🇹🇴', 'currency' => 'TOP'],
            'Tuvalu' => ['name' => ['en' => 'Tuvalu', 'ar' => 'توفالو'], 'code' => '688', 'flag' => '🇹🇻', 'currency' => 'AUD'],
            'Vanuatu' => ['name' => ['en' => 'Vanuatu', 'ar' => 'فانواتو'], 'code' => '678', 'flag' => '🇻🇺', 'currency' => 'VUV'],
            'Vietnam' => ['name' => ['en' => 'Vietnam', 'ar' => 'فيتنام'], 'code' => '84', 'flag' => '🇻🇳', 'currency' => 'VND'],



        ];
        $order = 1;
        foreach ($countries as $index => $country) {

            Country::create([
                'name' => $country['name'],
                'code' => $country['code'],
                'flag' => $country['flag'],
                'order' => $order++, 
                'currency' => $country['currency']
            ]);
        }
    }
}
